plugins:
  - prettier-plugin-multiline-arrays

# Core formatting
printWidth: 80
tabWidth: 2
useTabs: false
semi: false
singleQuote: true
quoteProps: as-needed
objectWrap: preserve
multilineArraysWrapThreshold: 0
trailingComma: all

# JSX specific
jsxSingleQuote: false

# Parser overrides for specific file types
overrides:
  - files: "*.md"
    options:
      printWidth: 80
      proseWrap: always
  - files: "*.{ts,tsx}"
    options:
      parser: typescript